name: Docker

on:
   push: 
     branches: ["main"]
jobs:
  run-docker:
    runs-on: docker-latest
    steps:
      - name: Build docker Images
        run: docker build -t my-app:${{ github.sha }} .
